name: Deploy to Oracle Cloud

on:
  push:
    branches:
      - main # main 브랜치에 push될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # 1. 프로젝트 폴더로 이동 (폴더가 없으면 에러 방지용으로 체크 추가 가능)
            cd ~/sms-verification

            # 2. 최신 코드 가져오기
            git pull origin main

            export SECRETS_PATH=/home/ubuntu/caps-api-old

            # 3. 도커 컴포즈 실행 (절대 경로 설정이 되어 있으므로 바로 빌드)
            # --build 옵션은 코드가 변했을 때 이미지를 새로 만듭니다.
            docker compose up -d --build

            # 4. 사용하지 않는 이전 이미지들 정리 (용량 부족 방지)
            docker image prune -f
